Repository thoth-station/s2i-pytorch-notebook, pull requests merged in 2020-11, with the labels that each got.

#5 Add Tensorboard
  Pipfile
  Pipfile.lock
Labels: size/L

#8 include version identifier file for the repo
  thoth/s2i-pytorch-notebook/__init__.py
Labels: size/S

#10 Release of version 0.0.2
  CHANGELOG.md
  thoth/s2i-pytorch-notebook/__init__.py
Labels: approved, bot, size/XS
